export default {
  FETCH_ALBUMS_START: 'FETCH_ALBUMS_START',
  FETCH_ALBUMS_SUCCESS: 'FETCH_ALBUMS_SUCCESS',
  FETCH_ALBUMS_FAILURE: 'FETCH_ALBUMS_FAILURE',

  FETCH_ALBUM_START: 'FETCH_ALBUM_START',
  FETCH_ALBUM_SUCCESS: 'FETCH_ALBUM_SUCCESS',
  FETCH_ALBUM_FAILURE: 'FETCH_ALBUM_FAILURE',

  FETCH_AUTHOR_START: 'FETCH_AUTHOR_START',
  FETCH_AUTHOR_SUCCESS: 'FETCH_AUTHOR_SUCCESS',
  FETCH_AUTHOR_FAILURE: 'FETCH_AUTHOR_FAILURE',
}

